# Numpy

In [1]:
import numpy as np

## create array

- (1)1차원 array

In [ ]:
a = np.array([1, 2, 3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


- (2)2차원 array

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


- array를 만드는 방법들.

In [ ]:
a = np.zeros((2,2))
b = np.ones((1,2))
c = np.full((2,2), 7)
d = np.eye(2)
e = np.random.random((2,2))
x = np.arange(5, 15) #(5 ~ 14)까지 배열 생성.


---

## Array_indexing

In [ ]:
a = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])

b = a[:2, 1:3] #0~1행, 1~2열 선택
print(b)

[[2 3]
 [6 7]]


`array_indexing을 통해 복사된 행렬의 값을 바꾸면, 원본도 바뀐다.`

In [6]:
print(a[0, 1])
b[0, 0] = 77
print(a[0,1])

2
77


`indexing 방식에 따라 rank가 결정됨을 주의하자`

In [7]:
a = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
row_1 = a[1, :]
row_2 = a[1:2, :]
row_3 = a[[1], :]
print(row_1.shape)
print(row_2.shape)
print(row_3.shape)

(4,)
(1, 4)
(1, 4)


`-가 붙으면, 뒤에서부터 연산한다`

In [8]:
a = np.array([1,2,3,4,5])
print(a[-1])

5


`1:7은 범위, 3은 stride(간격)이다.`

In [9]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
print(x[1:7:3])

[1 4]


---

## Advanced indexing

`x에 list를 넣어 각 list요소의 index를 찾을 수 있다.`

In [12]:
x = np.arange(5, 15)

print(x[np.array([4,2])])

[9 7]


## Repeat

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)
print(np.repeat(a, 3, axis=1))#열방향으로 요소 3번씩 추가.
print(np.repeat(a, 2, axis=1))
print(np.repeat(a, 2, axis=0))#행방향으로 요소 2번씩 추가.

[[1 2]
 [3 4]]
(2, 2)
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]
[[1 1 2 2]
 [3 3 4 4]]
[[1 2]
 [1 2]
 [3 4]
 [3 4]]


## Concatenate

In [21]:
print(a.flatten())
b = np.array([[5,6],[7,8]])
print(b)
print(np.concatenate((a,b),axis = 0))
print(np.concatenate((a,b),axis = 1))

[1 2 3 4]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## transpose

In [22]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

## reshape

In [25]:
a = np.arange(6)
print(a.reshape((2,-1,3)))
print(a.shape)

[[[0 1 2]]

 [[3 4 5]]]
(6,)


## vstack

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [27]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])